name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build shadowJar
        run: ./gradlew shadowJar --no-daemon -PreleaseVersion="v0.1.${{ github.run_number }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.${{ github.run_number }}
          name: EnthusiaVotes v0.1.${{ github.run_number }}
          files: build/libs/EnthusiaVotes-v0.1.${{ github.run_number }}.jar
          generate_release_notes: true
          fail_on_unmatched_files: true
          make_latest: true
